---
- name: deploy and start Apache
  hosts: all  
  tasks:
    - name: install and update apache pkg
      yum:
        name: httpd
        state: latest
        become: yes
        
    - name: install and update firewall pkg
      yum:
        name: firewalld
        state: latest
        become: yes

    - name: start and enable firewalld
      service:
        name: firewalld
        enabled: true
        state: started
        become: yes

    - name: create web content
      copy:
        content: "Welcome Cloudten Team from GITHUB"
        dest: /var/www/html/index.html

    - name: start and enable httpd
      service:
        name: httpd
        enabled: true
        state: started
        become: yes

    - name: open firewall for http
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
        become: yes
